package com.maideniles.maidensmaterials.init;


import com.maideniles.maidensmaterials.MarvelousMaterials;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.RegistryObject;

public class ModCreativeModeTabs {

    public static final DeferredRegister<CreativeModeTab> CREATIVE_MODE_TABS =
            DeferredRegister.create(Registries.CREATIVE_MODE_TAB, MarvelousMaterials.MOD_ID);


    public static final RegistryObject<CreativeModeTab> ITEMS = CREATIVE_MODE_TABS.register("items",
            () -> CreativeModeTab.builder().icon(() -> new ItemStack(ModBlocks.MAGENTA_BRICK_BLOCK.get()))
                    .title(Component.translatable("creativetab.items"))
                    .displayItems((parameters, output) -> {


//ITEMS//
                        // output.accept(ModItems.MARVELOUS_MANUAL.get());
                        //TOOLS//
                        output.accept(ModItems.PRUNING_SHEARS.get());
                        //ESSENCES//
                        output.accept(ModItems.EARTHEN_ESSENCE.get());
                        output.accept(ModItems.FLORAL_ESSENCE.get());
                        //HIDDEN--FOR BOOK PURPOSES//
                        //  output.accept(ModItems.EARTHEN_POTION_ITEM.get());
                        //   output.accept(ModItems.FLORAL_POTION_ITEM.get());
                        //BLOSSOMS//
                        output.accept(ModItems.CRABAPPLE_BLOSSOMS.get());
                        output.accept(ModItems.POINCIANA_BLOSSOMS.get());
                        output.accept(ModItems.LABURNUM_BLOSSOMS.get());
                        output.accept(ModItems.JADE_BLOSSOMS.get());
                        output.accept(ModItems.PAULOWNIA_BLOSSOMS.get());
                        output.accept(ModItems.WISTERIA_BLOSSOMS.get());
                        output.accept(ModItems.JACARANDA_BLOSSOMS.get());
                        output.accept(ModItems.DOGWOOD_BLOSSOMS.get());
                        output.accept(ModItems.SILVERBELL_BLOSSOMS.get());
//COLORED PIGMENTS//

                        output.accept(ModItems.RED_PIGMENT.get());
                        output.accept(ModItems.ORANGE_PIGMENT.get());
                        output.accept(ModItems.YELLOW_PIGMENT.get());
                        output.accept(ModItems.LIME_PIGMENT.get());
                        output.accept(ModItems.GREEN_PIGMENT.get());
                        output.accept(ModItems.CYAN_PIGMENT.get());
                        output.accept(ModItems.LIGHT_BLUE_PIGMENT.get());
                        output.accept(ModItems.BLUE_PIGMENT.get());
                        output.accept(ModItems.PURPLE_PIGMENT.get());
                        output.accept(ModItems.MAGENTA_PIGMENT.get());
                        output.accept(ModItems.PINK_PIGMENT.get());
                        output.accept(ModItems.WHITE_PIGMENT.get());
                        output.accept(ModItems.LIGHT_GRAY_PIGMENT.get());
                        output.accept(ModItems.GRAY_PIGMENT.get());
                        output.accept(ModItems.BLACK_PIGMENT.get());
                        output.accept(ModItems.BROWN_PIGMENT.get());
                        //COLORED CLAY//
                        output.accept(ModItems.RED_CLAY.get());
                        output.accept(ModItems.ORANGE_CLAY.get());
                        output.accept(ModItems.YELLOW_CLAY.get());
                        output.accept(ModItems.LIME_CLAY.get());
                        output.accept(ModItems.GREEN_CLAY.get());
                        output.accept(ModItems.CYAN_CLAY.get());
                        output.accept(ModItems.LIGHT_BLUE_CLAY.get());
                        output.accept(ModItems.BLUE_CLAY.get());
                        output.accept(ModItems.PURPLE_CLAY.get());
                        output.accept(ModItems.MAGENTA_CLAY.get());
                        output.accept(ModItems.PINK_CLAY.get());
                        output.accept(ModItems.WHITE_CLAY.get());
                        output.accept(ModItems.LIGHT_GRAY_CLAY.get());
                        output.accept(ModItems.GRAY_CLAY.get());
                        output.accept(ModItems.BLACK_CLAY.get());
                        output.accept(ModItems.BROWN_CLAY.get());
                        //COLORED CLAY BRICKS//
                        output.accept(ModItems.RED_BRICK.get());
                        output.accept(ModItems.ORANGE_BRICK.get());
                        output.accept(ModItems.YELLOW_BRICK.get());
                        output.accept(ModItems.LIME_BRICK.get());
                        output.accept(ModItems.GREEN_BRICK.get());
                        output.accept(ModItems.CYAN_BRICK.get());
                        output.accept(ModItems.LIGHT_BLUE_BRICK.get());
                        output.accept(ModItems.BLUE_BRICK.get());
                        output.accept(ModItems.PURPLE_BRICK.get());
                        output.accept(ModItems.MAGENTA_BRICK.get());
                        output.accept(ModItems.PINK_BRICK.get());
                        output.accept(ModItems.WHITE_BRICK.get());
                        output.accept(ModItems.LIGHT_GRAY_BRICK.get());
                        output.accept(ModItems.GRAY_BRICK.get());
                        output.accept(ModItems.BLACK_BRICK.get());
                        output.accept(ModItems.BROWN_BRICK.get());
                        //COLORED CLAY MIX//
                        output.accept(ModItems.RED_CLAY_MIX.get());
                        output.accept(ModItems.ORANGE_CLAY_MIX.get());
                        output.accept(ModItems.YELLOW_CLAY_MIX.get());
                        output.accept(ModItems.LIME_CLAY_MIX.get());
                        output.accept(ModItems.GREEN_CLAY_MIX.get());
                        output.accept(ModItems.CYAN_CLAY_MIX.get());
                        output.accept(ModItems.LIGHT_BLUE_CLAY_MIX.get());
                        output.accept(ModItems.BLUE_CLAY_MIX.get());
                        output.accept(ModItems.PURPLE_CLAY_MIX.get());
                        output.accept(ModItems.MAGENTA_CLAY_MIX.get());
                        output.accept(ModItems.PINK_CLAY_MIX.get());
                        output.accept(ModItems.WHITE_CLAY_MIX.get());
                        output.accept(ModItems.LIGHT_GRAY_CLAY_MIX.get());
                        output.accept(ModItems.GRAY_CLAY_MIX.get());
                        output.accept(ModItems.BLACK_CLAY_MIX.get());
                        output.accept(ModItems.BROWN_CLAY_MIX.get());
                        //COLORED CLAY VASES//
                        output.accept(ModItems.RED_CLAY_VASE.get());
                        output.accept(ModItems.ORANGE_CLAY_VASE.get());
                        output.accept(ModItems.YELLOW_CLAY_VASE.get());
                        output.accept(ModItems.LIME_CLAY_VASE.get());
                        output.accept(ModItems.GREEN_CLAY_VASE.get());
                        output.accept(ModItems.CYAN_CLAY_VASE.get());
                        output.accept(ModItems.LIGHT_BLUE_CLAY_VASE.get());
                        output.accept(ModItems.BLUE_CLAY_VASE.get());
                        output.accept(ModItems.PURPLE_CLAY_VASE.get());
                        output.accept(ModItems.MAGENTA_CLAY_VASE.get());
                        output.accept(ModItems.PINK_CLAY_VASE.get());
                        output.accept(ModItems.WHITE_CLAY_VASE.get());
                        output.accept(ModItems.LIGHT_GRAY_CLAY_VASE.get());
                        output.accept(ModItems.GRAY_CLAY_VASE.get());
                        output.accept(ModItems.BLACK_CLAY_VASE.get());
                        output.accept(ModItems.BROWN_CLAY_VASE.get());
//COLORED DYE BATHS//
                        output.accept(ModItems.RED_DYE_BATH.get());
                        output.accept(ModItems.ORANGE_DYE_BATH.get());
                        output.accept(ModItems.YELLOW_DYE_BATH.get());
                        output.accept(ModItems.LIME_DYE_BATH.get());
                        output.accept(ModItems.GREEN_DYE_BATH.get());
                        output.accept(ModItems.CYAN_DYE_BATH.get());
                        output.accept(ModItems.LIGHT_BLUE_DYE_BATH.get());
                        output.accept(ModItems.BLUE_DYE_BATH.get());
                        output.accept(ModItems.PURPLE_DYE_BATH.get());
                        output.accept(ModItems.MAGENTA_DYE_BATH.get());
                        output.accept(ModItems.PINK_DYE_BATH.get());
                        output.accept(ModItems.WHITE_DYE_BATH.get());
                        output.accept(ModItems.LIGHT_GRAY_DYE_BATH.get());
                        output.accept(ModItems.GRAY_DYE_BATH.get());
                        output.accept(ModItems.BLACK_DYE_BATH.get());
                        output.accept(ModItems.BROWN_DYE_BATH.get());
                        //WHITEWASH//
                        output.accept(ModItems.WHITEWASH.get());
//COLORED STAINS//
                        output.accept(ModItems.RED_STAIN.get());
                        output.accept(ModItems.ORANGE_STAIN.get());
                        output.accept(ModItems.YELLOW_STAIN.get());
                        output.accept(ModItems.LIME_STAIN.get());
                        output.accept(ModItems.GREEN_STAIN.get());
                        output.accept(ModItems.CYAN_STAIN.get());
                        output.accept(ModItems.LIGHT_BLUE_STAIN.get());
                        output.accept(ModItems.BLUE_STAIN.get());
                        output.accept(ModItems.PURPLE_STAIN.get());
                        output.accept(ModItems.MAGENTA_STAIN.get());
                        output.accept(ModItems.PINK_STAIN.get());
                        output.accept(ModItems.WHITE_STAIN.get());
                        output.accept(ModItems.LIGHT_GRAY_STAIN.get());
                        output.accept(ModItems.GRAY_STAIN.get());
                        output.accept(ModItems.BLACK_STAIN.get());
                        output.accept(ModItems.BROWN_STAIN.get());
                        //DOOR BLUEPRINTS//
                        output.accept(ModItems.DOOR_PLANS_1.get());
                        output.accept(ModItems.DOOR_PLANS_2.get());
                        output.accept(ModItems.DOOR_PLANS_3.get());
                        output.accept(ModItems.DOOR_PLANS_4.get());
                        output.accept(ModItems.DOOR_PLANS_5.get());
                        output.accept(ModItems.DOOR_PLANS_6.get());
                        //DARK IRON//
                        output.accept(ModItems.DARK_IRON_MIX.get());
                        output.accept(ModItems.DARK_IRON_INGOT.get());
                        output.accept(ModItems.DARK_IRON_INLAY.get());
                        //GROUT//
                        output.accept(ModItems.GROUT.get());
                        //MICA POWDER//
                        output.accept(ModItems.MICA_POWDER.get());
                        //GEMSTONES//
                        output.accept(ModItems.JASPER_CHUNK.get());
                        output.accept(ModItems.CARNELIAN_CHUNK.get());
                        output.accept(ModItems.CITRINE_CHUNK.get());
                        output.accept(ModItems.AVENTURINE_CHUNK.get());
                        output.accept(ModItems.JADE_CHUNK.get());
                        output.accept(ModItems.CHALCOPYRITE_CHUNK.get());
                        output.accept(ModItems.LABRADORITE_CHUNK.get());
                        output.accept(ModItems.MOONSTONE_CHUNK.get());
                        output.accept(ModItems.SODALITE_CHUNK.get());
                        output.accept(ModItems.AMETHYST_CHUNK.get());
                        output.accept(ModItems.ROSE_QUARTZ_CHUNK.get());
                        output.accept(ModItems.MICA_CHUNK.get());
                        //FRAGMENTS//
                        output.accept(ModItems.JASPER_FRAGMENTS.get());
                        output.accept(ModItems.CARNELIAN_FRAGMENTS.get());
                        output.accept(ModItems.CITRINE_FRAGMENTS.get());
                        output.accept(ModItems.AVENTURINE_FRAGMENTS.get());
                        output.accept(ModItems.JADE_FRAGMENTS.get());
                        output.accept(ModItems.CHALCOPYRITE_FRAGMENTS.get());
                        output.accept(ModItems.LABRADORITE_FRAGMENTS.get());
                        output.accept(ModItems.MOONSTONE_FRAGMENTS.get());
                        output.accept(ModItems.SODALITE_FRAGMENTS.get());
                        output.accept(ModItems.AMETHYST_FRAGMENTS.get());
                        output.accept(ModItems.ROSE_QUARTZ_FRAGMENTS.get());
                        output.accept(ModItems.MICA_FRAGMENTS.get());
                    })
                    .build());


    public static final RegistryObject<CreativeModeTab> WOOD = CREATIVE_MODE_TABS.register("wood",
            () -> CreativeModeTab.builder().icon(() -> new ItemStack(ModBlocks.MAGENTA_BRICK_BLOCK.get()))
                    .title(Component.translatable("creativetab.wood"))
                    .displayItems((parameters, output) -> {

                        //BLOCKS//
                        //LOGS//
                        output.accept(ModBlocks.CRABAPPLE_LOG.get());
                        output.accept(ModBlocks.POINCIANA_LOG.get());
                        output.accept(ModBlocks.LABURNUM_LOG.get());
                        output.accept(ModBlocks.JADE_LOG.get());
                        output.accept(ModBlocks.PAULOWNIA_LOG.get());
                        output.accept(ModBlocks.WISTERIA_LOG.get());
                        output.accept(ModBlocks.JACARANDA_LOG.get());
                        output.accept(ModBlocks.DOGWOOD_LOG.get());
                        output.accept(ModBlocks.SILVERBELL_LOG.get());
                        output.accept(ModBlocks.CEDAR_LOG.get());

                        output.accept(ModBlocks.STRIPPED_CRABAPPLE_LOG.get());
                        output.accept(ModBlocks.STRIPPED_POINCIANA_LOG.get());
                        output.accept(ModBlocks.STRIPPED_LABURNUM_LOG.get());
                        output.accept(ModBlocks.STRIPPED_JADE_LOG.get());
                        output.accept(ModBlocks.STRIPPED_PAULOWNIA_LOG.get());
                        output.accept(ModBlocks.STRIPPED_WISTERIA_LOG.get());
                        output.accept(ModBlocks.STRIPPED_JACARANDA_LOG.get());
                        output.accept(ModBlocks.STRIPPED_DOGWOOD_LOG.get());
                        output.accept(ModBlocks.STRIPPED_SILVERBELL_LOG.get());
                        output.accept(ModBlocks.STRIPPED_CEDAR_LOG.get());

                        //WOODS//
                        output.accept(ModBlocks.CRABAPPLE_WOOD.get());
                        output.accept(ModBlocks.POINCIANA_WOOD.get());
                        output.accept(ModBlocks.LABURNUM_WOOD.get());
                        output.accept(ModBlocks.JADE_WOOD.get());
                        output.accept(ModBlocks.PAULOWNIA_WOOD.get());
                        output.accept(ModBlocks.WISTERIA_WOOD.get());
                        output.accept(ModBlocks.JACARANDA_WOOD.get());
                        output.accept(ModBlocks.DOGWOOD_WOOD.get());
                        output.accept(ModBlocks.SILVERBELL_WOOD.get());
                        output.accept(ModBlocks.CEDAR_WOOD.get());

                        output.accept(ModBlocks.STRIPPED_CRABAPPLE_WOOD.get());
                        output.accept(ModBlocks.STRIPPED_POINCIANA_WOOD.get());
                        output.accept(ModBlocks.STRIPPED_LABURNUM_WOOD.get());
                        output.accept(ModBlocks.STRIPPED_JADE_WOOD.get());
                        output.accept(ModBlocks.STRIPPED_PAULOWNIA_WOOD.get());
                        output.accept(ModBlocks.STRIPPED_WISTERIA_WOOD.get());
                        output.accept(ModBlocks.STRIPPED_JACARANDA_WOOD.get());
                        output.accept(ModBlocks.STRIPPED_DOGWOOD_WOOD.get());
                        output.accept(ModBlocks.STRIPPED_SILVERBELL_WOOD.get());
                        output.accept(ModBlocks.STRIPPED_CEDAR_WOOD.get());
                        //LEAVES//
                        output.accept(ModBlocks.CRABAPPLE_LEAVES.get());
                        output.accept(ModBlocks.POINCIANA_LEAVES.get());
                        output.accept(ModBlocks.LABURNUM_LEAVES.get());
                        output.accept(ModBlocks.JADE_LEAVES.get());
                        output.accept(ModBlocks.PAULOWNIA_LEAVES.get());
                        output.accept(ModBlocks.WISTERIA_LEAVES.get());
                        output.accept(ModBlocks.JACARANDA_LEAVES.get());
                        output.accept(ModBlocks.DOGWOOD_LEAVES.get());
                        output.accept(ModBlocks.SILVERBELL_LEAVES.get());
                        output.accept(ModBlocks.CEDAR_LEAVES.get());
                        //VINES//
                        output.accept(ModBlocks.CRABAPPLE_VINE.get());
                        output.accept(ModBlocks.POINCIANA_VINE.get());
                        output.accept(ModBlocks.LABURNUM_VINE.get());
                        output.accept(ModBlocks.JADE_VINE.get());
                        output.accept(ModBlocks.PAULOWNIA_VINE.get());
                        output.accept(ModBlocks.WISTERIA_VINE.get());
                        output.accept(ModBlocks.JACARANDA_VINE.get());
                        output.accept(ModBlocks.DOGWOOD_VINE.get());
                        output.accept(ModBlocks.SILVERBELL_VINE.get());
                        output.accept(ModBlocks.CEDAR_VINE.get());
                        //SAPLINGS//
                        output.accept(ModBlocks.CRABAPPLE_SAPLING.get());
                        output.accept(ModBlocks.POINCIANA_SAPLING.get());
                        output.accept(ModBlocks.LABURNUM_SAPLING.get());
                        output.accept(ModBlocks.JADE_SAPLING.get());
                        output.accept(ModBlocks.PAULOWNIA_SAPLING.get());
                        output.accept(ModBlocks.WISTERIA_SAPLING.get());
                        output.accept(ModBlocks.JACARANDA_SAPLING.get());
                        output.accept(ModBlocks.DOGWOOD_SAPLING.get());
                        output.accept(ModBlocks.SILVERBELL_SAPLING.get());
                        output.accept(ModBlocks.CEDAR_SAPLING.get());
                        //WOOD BLOCKS//
                        output.accept(ModBlocks.CRABAPPLE_PLANKS.get());
                        output.accept(ModBlocks.POINCIANA_PLANKS.get());
                        output.accept(ModBlocks.LABURNUM_PLANKS.get());
                        output.accept(ModBlocks.JADE_PLANKS.get());
                        output.accept(ModBlocks.PAULOWNIA_PLANKS.get());
                        output.accept(ModBlocks.WISTERIA_PLANKS.get());
                        output.accept(ModBlocks.JACARANDA_PLANKS.get());
                        output.accept(ModBlocks.DOGWOOD_PLANKS.get());
                        output.accept(ModBlocks.SILVERBELL_PLANKS.get());
                        output.accept(ModBlocks.CEDAR_PLANKS.get());
                        //PLANKS//
                        output.accept(ModBlocks.CRABAPPLE_STAIRS.get());
                        output.accept(ModBlocks.POINCIANA_STAIRS.get());
                        output.accept(ModBlocks.LABURNUM_STAIRS.get());
                        output.accept(ModBlocks.JADE_STAIRS.get());
                        output.accept(ModBlocks.PAULOWNIA_STAIRS.get());
                        output.accept(ModBlocks.WISTERIA_STAIRS.get());
                        output.accept(ModBlocks.JACARANDA_STAIRS.get());
                        output.accept(ModBlocks.DOGWOOD_STAIRS.get());
                        output.accept(ModBlocks.SILVERBELL_STAIRS.get());
                        output.accept(ModBlocks.CEDAR_STAIRS.get());
                        //STAIRS//
                        output.accept(ModBlocks.CRABAPPLE_SLAB.get());
                        output.accept(ModBlocks.POINCIANA_SLAB.get());
                        output.accept(ModBlocks.LABURNUM_SLAB.get());
                        output.accept(ModBlocks.JADE_SLAB.get());
                        output.accept(ModBlocks.PAULOWNIA_SLAB.get());
                        output.accept(ModBlocks.WISTERIA_SLAB.get());
                        output.accept(ModBlocks.JACARANDA_SLAB.get());
                        output.accept(ModBlocks.DOGWOOD_SLAB.get());
                        output.accept(ModBlocks.SILVERBELL_SLAB.get());
                        output.accept(ModBlocks.CEDAR_SLAB.get());
                        //FENCES//
                        output.accept(ModBlocks.CRABAPPLE_FENCE.get());
                        output.accept(ModBlocks.POINCIANA_FENCE.get());
                        output.accept(ModBlocks.LABURNUM_FENCE.get());
                        output.accept(ModBlocks.JADE_FENCE.get());
                        output.accept(ModBlocks.PAULOWNIA_FENCE.get());
                        output.accept(ModBlocks.WISTERIA_FENCE.get());
                        output.accept(ModBlocks.JACARANDA_FENCE.get());
                        output.accept(ModBlocks.DOGWOOD_FENCE.get());
                        output.accept(ModBlocks.SILVERBELL_FENCE.get());
                        output.accept(ModBlocks.CEDAR_FENCE.get());
                        //GATES//
                        output.accept(ModBlocks.CRABAPPLE_FENCE_GATE.get());
                        output.accept(ModBlocks.POINCIANA_FENCE_GATE.get());
                        output.accept(ModBlocks.LABURNUM_FENCE_GATE.get());
                        output.accept(ModBlocks.JADE_FENCE_GATE.get());
                        output.accept(ModBlocks.PAULOWNIA_FENCE_GATE.get());
                        output.accept(ModBlocks.WISTERIA_FENCE_GATE.get());
                        output.accept(ModBlocks.JACARANDA_FENCE_GATE.get());
                        output.accept(ModBlocks.DOGWOOD_FENCE_GATE.get());
                        output.accept(ModBlocks.SILVERBELL_FENCE_GATE.get());
                        output.accept(ModBlocks.CEDAR_FENCE_GATE.get());
                        //PRESSURE PLATES//
                        output.accept(ModBlocks.CRABAPPLE_PRESSURE_PLATE.get());
                        output.accept(ModBlocks.POINCIANA_PRESSURE_PLATE.get());
                        output.accept(ModBlocks.LABURNUM_PRESSURE_PLATE.get());
                        output.accept(ModBlocks.JADE_PRESSURE_PLATE.get());
                        output.accept(ModBlocks.PAULOWNIA_PRESSURE_PLATE.get());
                        output.accept(ModBlocks.WISTERIA_PRESSURE_PLATE.get());
                        output.accept(ModBlocks.JACARANDA_PRESSURE_PLATE.get());
                        output.accept(ModBlocks.DOGWOOD_PRESSURE_PLATE.get());
                        output.accept(ModBlocks.SILVERBELL_PRESSURE_PLATE.get());
                        output.accept(ModBlocks.CEDAR_PRESSURE_PLATE.get());
                        //BUTTONS//
                        output.accept(ModBlocks.CRABAPPLE_BUTTON.get());
                        output.accept(ModBlocks.POINCIANA_BUTTON.get());
                        output.accept(ModBlocks.LABURNUM_BUTTON.get());
                        output.accept(ModBlocks.JADE_BUTTON.get());
                        output.accept(ModBlocks.PAULOWNIA_BUTTON.get());
                        output.accept(ModBlocks.WISTERIA_BUTTON.get());
                        output.accept(ModBlocks.JACARANDA_BUTTON.get());
                        output.accept(ModBlocks.DOGWOOD_BUTTON.get());
                        output.accept(ModBlocks.SILVERBELL_BUTTON.get());
                        output.accept(ModBlocks.CEDAR_BUTTON.get());
                        //BOOKSHELVES//
                        output.accept(ModBlocks.CRABAPPLE_BOOKSHELF.get());
                        output.accept(ModBlocks.POINCIANA_BOOKSHELF.get());
                        output.accept(ModBlocks.LABURNUM_BOOKSHELF.get());
                        output.accept(ModBlocks.JADE_BOOKSHELF.get());
                        output.accept(ModBlocks.PAULOWNIA_BOOKSHELF.get());
                        output.accept(ModBlocks.WISTERIA_BOOKSHELF.get());
                        output.accept(ModBlocks.JACARANDA_BOOKSHELF.get());
                        output.accept(ModBlocks.DOGWOOD_BOOKSHELF.get());
                        output.accept(ModBlocks.SILVERBELL_BOOKSHELF.get());
                        output.accept(ModBlocks.CEDAR_BOOKSHELF.get());

                        output.accept(ModBlocks.ACACIA_CHEST.get());
                        output.accept(ModBlocks.BIRCH_CHEST.get());
                        output.accept(ModBlocks.OAK_CHEST.get());
                        output.accept(ModBlocks.SPRUCE_CHEST.get());
                        output.accept(ModBlocks.DARK_OAK_CHEST.get());
                        output.accept(ModBlocks.JUNGLE_CHEST.get());
                        output.accept(ModBlocks.CRIMSON_CHEST.get());
                        output.accept(ModBlocks.WARPED_CHEST.get());

                        output.accept(ModBlocks.CRABAPPLE_CHEST.get());
                        output.accept(ModBlocks.POINCIANA_CHEST.get());
                        output.accept(ModBlocks.LABURNUM_CHEST.get());
                        output.accept(ModBlocks.JADE_CHEST.get());
                        output.accept(ModBlocks.PAULOWNIA_CHEST.get());
                        output.accept(ModBlocks.WISTERIA_CHEST.get());
                        output.accept(ModBlocks.JACARANDA_CHEST.get());
                        output.accept(ModBlocks.DOGWOOD_CHEST.get());
                        output.accept(ModBlocks.SILVERBELL_CHEST.get());
                        output.accept(ModBlocks.CEDAR_CHEST.get());
                        //DOORS//
                        //DOOR 1//
                        output.accept(ModBlocks.CRABAPPLE_DOOR_1.get());
                        output.accept(ModBlocks.POINCIANA_DOOR_1.get());
                        output.accept(ModBlocks.LABURNUM_DOOR_1.get());
                        output.accept(ModBlocks.JADE_DOOR_1.get());
                        output.accept(ModBlocks.PAULOWNIA_DOOR_1.get());
                        output.accept(ModBlocks.WISTERIA_DOOR_1.get());
                        output.accept(ModBlocks.JACARANDA_DOOR_1.get());
                        output.accept(ModBlocks.DOGWOOD_DOOR_1.get());
                        output.accept(ModBlocks.SILVERBELL_DOOR_1.get());
                        output.accept(ModBlocks.CEDAR_DOOR_1.get());
                        //DOOR 2//
                        output.accept(ModBlocks.CRABAPPLE_DOOR_2.get());
                        output.accept(ModBlocks.POINCIANA_DOOR_2.get());
                        output.accept(ModBlocks.LABURNUM_DOOR_2.get());
                        output.accept(ModBlocks.JADE_DOOR_2.get());
                        output.accept(ModBlocks.PAULOWNIA_DOOR_2.get());
                        output.accept(ModBlocks.WISTERIA_DOOR_2.get());
                        output.accept(ModBlocks.JACARANDA_DOOR_2.get());
                        output.accept(ModBlocks.DOGWOOD_DOOR_2.get());
                        output.accept(ModBlocks.SILVERBELL_DOOR_2.get());
                        output.accept(ModBlocks.CEDAR_DOOR_2.get());
                        //DOOR 3//
                        output.accept(ModBlocks.CRABAPPLE_DOOR_3.get());
                        output.accept(ModBlocks.POINCIANA_DOOR_3.get());
                        output.accept(ModBlocks.LABURNUM_DOOR_3.get());
                        output.accept(ModBlocks.JADE_DOOR_3.get());
                        output.accept(ModBlocks.PAULOWNIA_DOOR_3.get());
                        output.accept(ModBlocks.WISTERIA_DOOR_3.get());
                        output.accept(ModBlocks.JACARANDA_DOOR_3.get());
                        output.accept(ModBlocks.DOGWOOD_DOOR_3.get());
                        output.accept(ModBlocks.SILVERBELL_DOOR_3.get());
                        output.accept(ModBlocks.CEDAR_DOOR_3.get());
                        //DOOR 4//
                        output.accept(ModBlocks.CRABAPPLE_DOOR_4.get());
                        output.accept(ModBlocks.POINCIANA_DOOR_4.get());
                        output.accept(ModBlocks.LABURNUM_DOOR_4.get());
                        output.accept(ModBlocks.JADE_DOOR_4.get());
                        output.accept(ModBlocks.PAULOWNIA_DOOR_4.get());
                        output.accept(ModBlocks.WISTERIA_DOOR_4.get());
                        output.accept(ModBlocks.JACARANDA_DOOR_4.get());
                        output.accept(ModBlocks.DOGWOOD_DOOR_4.get());
                        output.accept(ModBlocks.SILVERBELL_DOOR_4.get());
                        output.accept(ModBlocks.CEDAR_DOOR_4.get());
                        //DOOR 5//
                        output.accept(ModBlocks.CRABAPPLE_DOOR_5.get());
                        output.accept(ModBlocks.POINCIANA_DOOR_5.get());
                        output.accept(ModBlocks.LABURNUM_DOOR_5.get());
                        output.accept(ModBlocks.JADE_DOOR_5.get());
                        output.accept(ModBlocks.PAULOWNIA_DOOR_5.get());
                        output.accept(ModBlocks.WISTERIA_DOOR_5.get());
                        output.accept(ModBlocks.JACARANDA_DOOR_5.get());
                        output.accept(ModBlocks.DOGWOOD_DOOR_5.get());
                        output.accept(ModBlocks.SILVERBELL_DOOR_5.get());
                        output.accept(ModBlocks.CEDAR_DOOR_5.get());
                        //DOOR 6//
                        output.accept(ModBlocks.CRABAPPLE_DOOR_6.get());
                        output.accept(ModBlocks.POINCIANA_DOOR_6.get());
                        output.accept(ModBlocks.LABURNUM_DOOR_6.get());
                        output.accept(ModBlocks.JADE_DOOR_6.get());
                        output.accept(ModBlocks.PAULOWNIA_DOOR_6.get());
                        output.accept(ModBlocks.WISTERIA_DOOR_6.get());
                        output.accept(ModBlocks.JACARANDA_DOOR_6.get());
                        output.accept(ModBlocks.DOGWOOD_DOOR_6.get());
                        output.accept(ModBlocks.SILVERBELL_DOOR_6.get());
                        output.accept(ModBlocks.CEDAR_DOOR_6.get());
//TRAPDOORS//
                        //TRAPDOOR 1//
                        output.accept(ModBlocks.CRABAPPLE_TRAPDOOR_1.get());
                        output.accept(ModBlocks.POINCIANA_TRAPDOOR_1.get());
                        output.accept(ModBlocks.LABURNUM_TRAPDOOR_1.get());
                        output.accept(ModBlocks.JADE_TRAPDOOR_1.get());
                        output.accept(ModBlocks.PAULOWNIA_TRAPDOOR_1.get());
                        output.accept(ModBlocks.WISTERIA_TRAPDOOR_1.get());
                        output.accept(ModBlocks.JACARANDA_TRAPDOOR_1.get());
                        output.accept(ModBlocks.DOGWOOD_TRAPDOOR_1.get());
                        output.accept(ModBlocks.SILVERBELL_TRAPDOOR_1.get());
                        output.accept(ModBlocks.CEDAR_TRAPDOOR_1.get());
                        //TRAPDOOR 2//
                        output.accept(ModBlocks.CRABAPPLE_TRAPDOOR_2.get());
                        output.accept(ModBlocks.POINCIANA_TRAPDOOR_2.get());
                        output.accept(ModBlocks.LABURNUM_TRAPDOOR_2.get());
                        output.accept(ModBlocks.JADE_TRAPDOOR_2.get());
                        output.accept(ModBlocks.PAULOWNIA_TRAPDOOR_2.get());
                        output.accept(ModBlocks.WISTERIA_TRAPDOOR_2.get());
                        output.accept(ModBlocks.JACARANDA_TRAPDOOR_2.get());
                        output.accept(ModBlocks.DOGWOOD_TRAPDOOR_2.get());
                        output.accept(ModBlocks.SILVERBELL_TRAPDOOR_2.get());
                        output.accept(ModBlocks.CEDAR_TRAPDOOR_2.get());
                        //TRAPDOOR 3//
                        output.accept(ModBlocks.CRABAPPLE_TRAPDOOR_3.get());
                        output.accept(ModBlocks.POINCIANA_TRAPDOOR_3.get());
                        output.accept(ModBlocks.LABURNUM_TRAPDOOR_3.get());
                        output.accept(ModBlocks.JADE_TRAPDOOR_3.get());
                        output.accept(ModBlocks.PAULOWNIA_TRAPDOOR_3.get());
                        output.accept(ModBlocks.WISTERIA_TRAPDOOR_3.get());
                        output.accept(ModBlocks.JACARANDA_TRAPDOOR_3.get());
                        output.accept(ModBlocks.DOGWOOD_TRAPDOOR_3.get());
                        output.accept(ModBlocks.SILVERBELL_TRAPDOOR_3.get());
                        output.accept(ModBlocks.CEDAR_TRAPDOOR_3.get());
                        //TRAPDOOR 4//
                        output.accept(ModBlocks.CRABAPPLE_TRAPDOOR_4.get());
                        output.accept(ModBlocks.POINCIANA_TRAPDOOR_4.get());
                        output.accept(ModBlocks.LABURNUM_TRAPDOOR_4.get());
                        output.accept(ModBlocks.JADE_TRAPDOOR_4.get());
                        output.accept(ModBlocks.PAULOWNIA_TRAPDOOR_4.get());
                        output.accept(ModBlocks.WISTERIA_TRAPDOOR_4.get());
                        output.accept(ModBlocks.JACARANDA_TRAPDOOR_4.get());
                        output.accept(ModBlocks.DOGWOOD_TRAPDOOR_4.get());
                        output.accept(ModBlocks.SILVERBELL_TRAPDOOR_4.get());
                        output.accept(ModBlocks.CEDAR_TRAPDOOR_4.get());
//WHITEWASHED//
                        output.accept(ModBlocks.WHITEWASHED_PLANKS.get());
                        output.accept(ModBlocks.WHITEWASHED_STAIRS.get());
                        output.accept(ModBlocks.WHITEWASHED_SLAB.get());
                        output.accept(ModBlocks.WHITEWASHED_FENCE.get());
                        output.accept(ModBlocks.WHITEWASHED_FENCE_GATE.get());
                        output.accept(ModBlocks.WHITEWASHED_PRESSURE_PLATE.get());
                        output.accept(ModBlocks.WHITEWASHED_BUTTON.get());
                        //STAINED//
                        //PLANKS//

                        output.accept(ModBlocks.RED_STAINED_PLANKS.get());
                        output.accept(ModBlocks.ORANGE_STAINED_PLANKS.get());
                        output.accept(ModBlocks.YELLOW_STAINED_PLANKS.get());
                        output.accept(ModBlocks.LIME_STAINED_PLANKS.get());
                        output.accept(ModBlocks.GREEN_STAINED_PLANKS.get());
                        output.accept(ModBlocks.CYAN_STAINED_PLANKS.get());
                        output.accept(ModBlocks.LIGHT_BLUE_STAINED_PLANKS.get());
                        output.accept(ModBlocks.BLUE_STAINED_PLANKS.get());
                        output.accept(ModBlocks.PURPLE_STAINED_PLANKS.get());
                        output.accept(ModBlocks.MAGENTA_STAINED_PLANKS.get());
                        output.accept(ModBlocks.PINK_STAINED_PLANKS.get());
                        output.accept(ModBlocks.WHITE_STAINED_PLANKS.get());
                        output.accept(ModBlocks.LIGHT_GRAY_STAINED_PLANKS.get());
                        output.accept(ModBlocks.GRAY_STAINED_PLANKS.get());
                        output.accept(ModBlocks.BLACK_STAINED_PLANKS.get());
                        output.accept(ModBlocks.BROWN_STAINED_PLANKS.get());

                        //STAIRS//

                        output.accept(ModBlocks.RED_STAINED_STAIRS.get());
                        output.accept(ModBlocks.ORANGE_STAINED_STAIRS.get());
                        output.accept(ModBlocks.YELLOW_STAINED_STAIRS.get());
                        output.accept(ModBlocks.LIME_STAINED_STAIRS.get());
                        output.accept(ModBlocks.GREEN_STAINED_STAIRS.get());
                        output.accept(ModBlocks.CYAN_STAINED_STAIRS.get());
                        output.accept(ModBlocks.LIGHT_BLUE_STAINED_STAIRS.get());
                        output.accept(ModBlocks.BLUE_STAINED_STAIRS.get());
                        output.accept(ModBlocks.PURPLE_STAINED_STAIRS.get());
                        output.accept(ModBlocks.MAGENTA_STAINED_STAIRS.get());
                        output.accept(ModBlocks.PINK_STAINED_STAIRS.get());
                        output.accept(ModBlocks.WHITE_STAINED_STAIRS.get());
                        output.accept(ModBlocks.LIGHT_GRAY_STAINED_STAIRS.get());
                        output.accept(ModBlocks.GRAY_STAINED_STAIRS.get());
                        output.accept(ModBlocks.BLACK_STAINED_STAIRS.get());
                        output.accept(ModBlocks.BROWN_STAINED_STAIRS.get());
                        //SLABS//

                        output.accept(ModBlocks.RED_STAINED_SLAB.get());
                        output.accept(ModBlocks.ORANGE_STAINED_SLAB.get());
                        output.accept(ModBlocks.YELLOW_STAINED_SLAB.get());
                        output.accept(ModBlocks.LIME_STAINED_SLAB.get());
                        output.accept(ModBlocks.GREEN_STAINED_SLAB.get());
                        output.accept(ModBlocks.CYAN_STAINED_SLAB.get());
                        output.accept(ModBlocks.LIGHT_BLUE_STAINED_SLAB.get());
                        output.accept(ModBlocks.BLUE_STAINED_SLAB.get());
                        output.accept(ModBlocks.PURPLE_STAINED_SLAB.get());
                        output.accept(ModBlocks.MAGENTA_STAINED_SLAB.get());
                        output.accept(ModBlocks.PINK_STAINED_SLAB.get());
                        output.accept(ModBlocks.WHITE_STAINED_SLAB.get());
                        output.accept(ModBlocks.LIGHT_GRAY_STAINED_SLAB.get());
                        output.accept(ModBlocks.GRAY_STAINED_SLAB.get());
                        output.accept(ModBlocks.BLACK_STAINED_SLAB.get());
                        output.accept(ModBlocks.BROWN_STAINED_SLAB.get());
                        //FENCES//

                        output.accept(ModBlocks.RED_STAINED_FENCE.get());
                        output.accept(ModBlocks.ORANGE_STAINED_FENCE.get());
                        output.accept(ModBlocks.YELLOW_STAINED_FENCE.get());
                        output.accept(ModBlocks.LIME_STAINED_FENCE.get());
                        output.accept(ModBlocks.GREEN_STAINED_FENCE.get());
                        output.accept(ModBlocks.CYAN_STAINED_FENCE.get());
                        output.accept(ModBlocks.LIGHT_BLUE_STAINED_FENCE.get());
                        output.accept(ModBlocks.BLUE_STAINED_FENCE.get());
                        output.accept(ModBlocks.PURPLE_STAINED_FENCE.get());
                        output.accept(ModBlocks.MAGENTA_STAINED_FENCE.get());
                        output.accept(ModBlocks.PINK_STAINED_FENCE.get());
                        output.accept(ModBlocks.WHITE_STAINED_FENCE.get());
                        output.accept(ModBlocks.LIGHT_GRAY_STAINED_FENCE.get());
                        output.accept(ModBlocks.GRAY_STAINED_FENCE.get());
                        output.accept(ModBlocks.BLACK_STAINED_FENCE.get());
                        output.accept(ModBlocks.BROWN_STAINED_FENCE.get());
                        //GATES//

                        output.accept(ModBlocks.RED_STAINED_FENCE_GATE.get());
                        output.accept(ModBlocks.ORANGE_STAINED_FENCE_GATE.get());
                        output.accept(ModBlocks.YELLOW_STAINED_FENCE_GATE.get());
                        output.accept(ModBlocks.LIME_STAINED_FENCE_GATE.get());
                        output.accept(ModBlocks.GREEN_STAINED_FENCE_GATE.get());
                        output.accept(ModBlocks.CYAN_STAINED_FENCE_GATE.get());
                        output.accept(ModBlocks.LIGHT_BLUE_STAINED_FENCE_GATE.get());
                        output.accept(ModBlocks.BLUE_STAINED_FENCE_GATE.get());
                        output.accept(ModBlocks.PURPLE_STAINED_FENCE_GATE.get());
                        output.accept(ModBlocks.MAGENTA_STAINED_FENCE_GATE.get());
                        output.accept(ModBlocks.PINK_STAINED_FENCE_GATE.get());
                        output.accept(ModBlocks.WHITE_STAINED_FENCE_GATE.get());
                        output.accept(ModBlocks.LIGHT_GRAY_STAINED_FENCE_GATE.get());
                        output.accept(ModBlocks.GRAY_STAINED_FENCE_GATE.get());
                        output.accept(ModBlocks.BLACK_STAINED_FENCE_GATE.get());
                        output.accept(ModBlocks.BROWN_STAINED_FENCE_GATE.get());
                        //PRESSURE PLATES//

                        output.accept(ModBlocks.RED_STAINED_PRESSURE_PLATE.get());
                        output.accept(ModBlocks.ORANGE_STAINED_PRESSURE_PLATE.get());
                        output.accept(ModBlocks.YELLOW_STAINED_PRESSURE_PLATE.get());
                        output.accept(ModBlocks.LIME_STAINED_PRESSURE_PLATE.get());
                        output.accept(ModBlocks.GREEN_STAINED_PRESSURE_PLATE.get());
                        output.accept(ModBlocks.CYAN_STAINED_PRESSURE_PLATE.get());
                        output.accept(ModBlocks.LIGHT_BLUE_STAINED_PRESSURE_PLATE.get());
                        output.accept(ModBlocks.BLUE_STAINED_PRESSURE_PLATE.get());
                        output.accept(ModBlocks.PURPLE_STAINED_PRESSURE_PLATE.get());
                        output.accept(ModBlocks.MAGENTA_STAINED_PRESSURE_PLATE.get());
                        output.accept(ModBlocks.PINK_STAINED_PRESSURE_PLATE.get());
                        output.accept(ModBlocks.WHITE_STAINED_PRESSURE_PLATE.get());
                        output.accept(ModBlocks.LIGHT_GRAY_STAINED_PRESSURE_PLATE.get());
                        output.accept(ModBlocks.GRAY_STAINED_PRESSURE_PLATE.get());
                        output.accept(ModBlocks.BLACK_STAINED_PRESSURE_PLATE.get());
                        output.accept(ModBlocks.BROWN_STAINED_PRESSURE_PLATE.get());
                        //BUTTONS//

                        output.accept(ModBlocks.RED_STAINED_BUTTON.get());
                        output.accept(ModBlocks.ORANGE_STAINED_BUTTON.get());
                        output.accept(ModBlocks.YELLOW_STAINED_BUTTON.get());
                        output.accept(ModBlocks.LIME_STAINED_BUTTON.get());
                        output.accept(ModBlocks.GREEN_STAINED_BUTTON.get());
                        output.accept(ModBlocks.CYAN_STAINED_BUTTON.get());
                        output.accept(ModBlocks.LIGHT_BLUE_STAINED_BUTTON.get());
                        output.accept(ModBlocks.BLUE_STAINED_BUTTON.get());
                        output.accept(ModBlocks.PURPLE_STAINED_BUTTON.get());
                        output.accept(ModBlocks.MAGENTA_STAINED_BUTTON.get());
                        output.accept(ModBlocks.PINK_STAINED_BUTTON.get());
                        output.accept(ModBlocks.WHITE_STAINED_BUTTON.get());
                        output.accept(ModBlocks.LIGHT_GRAY_STAINED_BUTTON.get());
                        output.accept(ModBlocks.GRAY_STAINED_BUTTON.get());
                        output.accept(ModBlocks.BLACK_STAINED_BUTTON.get());
                        output.accept(ModBlocks.BROWN_STAINED_BUTTON.get());
                        //BOOKSHELVES//
                        output.accept(ModBlocks.RED_STAINED_BOOKSHELF.get());
                        output.accept(ModBlocks.ORANGE_STAINED_BOOKSHELF.get());
                        output.accept(ModBlocks.YELLOW_STAINED_BOOKSHELF.get());
                        output.accept(ModBlocks.LIME_STAINED_BOOKSHELF.get());
                        output.accept(ModBlocks.GREEN_STAINED_BOOKSHELF.get());
                        output.accept(ModBlocks.CYAN_STAINED_BOOKSHELF.get());
                        output.accept(ModBlocks.LIGHT_BLUE_STAINED_BOOKSHELF.get());
                        output.accept(ModBlocks.BLUE_STAINED_BOOKSHELF.get());
                        output.accept(ModBlocks.PURPLE_STAINED_BOOKSHELF.get());
                        output.accept(ModBlocks.MAGENTA_STAINED_BOOKSHELF.get());
                        output.accept(ModBlocks.PINK_STAINED_BOOKSHELF.get());
                        output.accept(ModBlocks.WHITE_STAINED_BOOKSHELF.get());
                        output.accept(ModBlocks.LIGHT_GRAY_STAINED_BOOKSHELF.get());
                        output.accept(ModBlocks.GRAY_STAINED_BOOKSHELF.get());
                        output.accept(ModBlocks.BLACK_STAINED_BOOKSHELF.get());
                        output.accept(ModBlocks.BROWN_STAINED_BOOKSHELF.get());
                        //DOORS//
                        //DOOR 1//
                        output.accept(ModBlocks.RED_STAINED_DOOR_1.get());
                        output.accept(ModBlocks.ORANGE_STAINED_DOOR_1.get());
                        output.accept(ModBlocks.YELLOW_STAINED_DOOR_1.get());
                        output.accept(ModBlocks.LIME_STAINED_DOOR_1.get());
                        output.accept(ModBlocks.GREEN_STAINED_DOOR_1.get());
                        output.accept(ModBlocks.CYAN_STAINED_DOOR_1.get());
                        output.accept(ModBlocks.LIGHT_BLUE_STAINED_DOOR_1.get());
                        output.accept(ModBlocks.BLUE_STAINED_DOOR_1.get());
                        output.accept(ModBlocks.PURPLE_STAINED_DOOR_1.get());
                        output.accept(ModBlocks.MAGENTA_STAINED_DOOR_1.get());
                        output.accept(ModBlocks.PINK_STAINED_DOOR_1.get());
                        output.accept(ModBlocks.WHITE_STAINED_DOOR_1.get());
                        output.accept(ModBlocks.LIGHT_GRAY_STAINED_DOOR_1.get());
                        output.accept(ModBlocks.GRAY_STAINED_DOOR_1.get());
                        output.accept(ModBlocks.BLACK_STAINED_DOOR_1.get());
                        output.accept(ModBlocks.BROWN_STAINED_DOOR_1.get());
//DOOR 2//
                        output.accept(ModBlocks.RED_STAINED_DOOR_2.get());
                        output.accept(ModBlocks.ORANGE_STAINED_DOOR_2.get());
                        output.accept(ModBlocks.YELLOW_STAINED_DOOR_2.get());
                        output.accept(ModBlocks.LIME_STAINED_DOOR_2.get());
                        output.accept(ModBlocks.GREEN_STAINED_DOOR_2.get());
                        output.accept(ModBlocks.CYAN_STAINED_DOOR_2.get());
                        output.accept(ModBlocks.LIGHT_BLUE_STAINED_DOOR_2.get());
                        output.accept(ModBlocks.BLUE_STAINED_DOOR_2.get());
                        output.accept(ModBlocks.PURPLE_STAINED_DOOR_2.get());
                        output.accept(ModBlocks.MAGENTA_STAINED_DOOR_2.get());
                        output.accept(ModBlocks.PINK_STAINED_DOOR_2.get());
                        output.accept(ModBlocks.WHITE_STAINED_DOOR_2.get());
                        output.accept(ModBlocks.LIGHT_GRAY_STAINED_DOOR_2.get());
                        output.accept(ModBlocks.GRAY_STAINED_DOOR_2.get());
                        output.accept(ModBlocks.BLACK_STAINED_DOOR_2.get());
                        output.accept(ModBlocks.BROWN_STAINED_DOOR_2.get());
//DOOR 3//
                        output.accept(ModBlocks.RED_STAINED_DOOR_3.get());
                        output.accept(ModBlocks.ORANGE_STAINED_DOOR_3.get());
                        output.accept(ModBlocks.YELLOW_STAINED_DOOR_3.get());
                        output.accept(ModBlocks.LIME_STAINED_DOOR_3.get());
                        output.accept(ModBlocks.GREEN_STAINED_DOOR_3.get());
                        output.accept(ModBlocks.CYAN_STAINED_DOOR_3.get());
                        output.accept(ModBlocks.LIGHT_BLUE_STAINED_DOOR_3.get());
                        output.accept(ModBlocks.BLUE_STAINED_DOOR_3.get());
                        output.accept(ModBlocks.PURPLE_STAINED_DOOR_3.get());
                        output.accept(ModBlocks.MAGENTA_STAINED_DOOR_3.get());
                        output.accept(ModBlocks.PINK_STAINED_DOOR_3.get());
                        output.accept(ModBlocks.WHITE_STAINED_DOOR_3.get());
                        output.accept(ModBlocks.LIGHT_GRAY_STAINED_DOOR_3.get());
                        output.accept(ModBlocks.GRAY_STAINED_DOOR_3.get());
                        output.accept(ModBlocks.BLACK_STAINED_DOOR_3.get());
                        output.accept(ModBlocks.BROWN_STAINED_DOOR_3.get());
//DOOR 4//
                        output.accept(ModBlocks.RED_STAINED_DOOR_4.get());
                        output.accept(ModBlocks.ORANGE_STAINED_DOOR_4.get());
                        output.accept(ModBlocks.YELLOW_STAINED_DOOR_4.get());
                        output.accept(ModBlocks.LIME_STAINED_DOOR_4.get());
                        output.accept(ModBlocks.GREEN_STAINED_DOOR_4.get());
                        output.accept(ModBlocks.CYAN_STAINED_DOOR_4.get());
                        output.accept(ModBlocks.LIGHT_BLUE_STAINED_DOOR_4.get());
                        output.accept(ModBlocks.BLUE_STAINED_DOOR_4.get());
                        output.accept(ModBlocks.PURPLE_STAINED_DOOR_4.get());
                        output.accept(ModBlocks.MAGENTA_STAINED_DOOR_4.get());
                        output.accept(ModBlocks.PINK_STAINED_DOOR_4.get());
                        output.accept(ModBlocks.WHITE_STAINED_DOOR_4.get());
                        output.accept(ModBlocks.LIGHT_GRAY_STAINED_DOOR_4.get());
                        output.accept(ModBlocks.GRAY_STAINED_DOOR_4.get());
                        output.accept(ModBlocks.BLACK_STAINED_DOOR_4.get());
                        output.accept(ModBlocks.BROWN_STAINED_DOOR_4.get());
//DOOR 5//
                        output.accept(ModBlocks.RED_STAINED_DOOR_5.get());
                        output.accept(ModBlocks.ORANGE_STAINED_DOOR_5.get());
                        output.accept(ModBlocks.YELLOW_STAINED_DOOR_5.get());
                        output.accept(ModBlocks.LIME_STAINED_DOOR_5.get());
                        output.accept(ModBlocks.GREEN_STAINED_DOOR_5.get());
                        output.accept(ModBlocks.CYAN_STAINED_DOOR_5.get());
                        output.accept(ModBlocks.LIGHT_BLUE_STAINED_DOOR_5.get());
                        output.accept(ModBlocks.BLUE_STAINED_DOOR_5.get());
                        output.accept(ModBlocks.PURPLE_STAINED_DOOR_5.get());
                        output.accept(ModBlocks.MAGENTA_STAINED_DOOR_5.get());
                        output.accept(ModBlocks.PINK_STAINED_DOOR_5.get());
                        output.accept(ModBlocks.WHITE_STAINED_DOOR_5.get());
                        output.accept(ModBlocks.LIGHT_GRAY_STAINED_DOOR_5.get());
                        output.accept(ModBlocks.GRAY_STAINED_DOOR_5.get());
                        output.accept(ModBlocks.BLACK_STAINED_DOOR_5.get());
                        output.accept(ModBlocks.BROWN_STAINED_DOOR_5.get());
//DOOR6//
                        output.accept(ModBlocks.RED_STAINED_DOOR_6.get());
                        output.accept(ModBlocks.ORANGE_STAINED_DOOR_6.get());
                        output.accept(ModBlocks.YELLOW_STAINED_DOOR_6.get());
                        output.accept(ModBlocks.LIME_STAINED_DOOR_6.get());
                        output.accept(ModBlocks.GREEN_STAINED_DOOR_6.get());
                        output.accept(ModBlocks.CYAN_STAINED_DOOR_6.get());
                        output.accept(ModBlocks.LIGHT_BLUE_STAINED_DOOR_6.get());
                        output.accept(ModBlocks.BLUE_STAINED_DOOR_6.get());
                        output.accept(ModBlocks.PURPLE_STAINED_DOOR_6.get());
                        output.accept(ModBlocks.MAGENTA_STAINED_DOOR_6.get());
                        output.accept(ModBlocks.PINK_STAINED_DOOR_6.get());
                        output.accept(ModBlocks.WHITE_STAINED_DOOR_6.get());
                        output.accept(ModBlocks.LIGHT_GRAY_STAINED_DOOR_6.get());
                        output.accept(ModBlocks.GRAY_STAINED_DOOR_6.get());
                        output.accept(ModBlocks.BLACK_STAINED_DOOR_6.get());
                        output.accept(ModBlocks.BROWN_STAINED_DOOR_6.get());

                        //TRAPDOOR 1//
                        output.accept(ModBlocks.RED_STAINED_TRAPDOOR_1.get());
                        output.accept(ModBlocks.ORANGE_STAINED_TRAPDOOR_1.get());
                        output.accept(ModBlocks.YELLOW_STAINED_TRAPDOOR_1.get());
                        output.accept(ModBlocks.LIME_STAINED_TRAPDOOR_1.get());
                        output.accept(ModBlocks.GREEN_STAINED_TRAPDOOR_1.get());
                        output.accept(ModBlocks.CYAN_STAINED_TRAPDOOR_1.get());
                        output.accept(ModBlocks.LIGHT_BLUE_STAINED_TRAPDOOR_1.get());
                        output.accept(ModBlocks.BLUE_STAINED_TRAPDOOR_1.get());
                        output.accept(ModBlocks.PURPLE_STAINED_TRAPDOOR_1.get());
                        output.accept(ModBlocks.MAGENTA_STAINED_TRAPDOOR_1.get());
                        output.accept(ModBlocks.PINK_STAINED_TRAPDOOR_1.get());
                        output.accept(ModBlocks.WHITE_STAINED_TRAPDOOR_1.get());
                        output.accept(ModBlocks.LIGHT_GRAY_STAINED_TRAPDOOR_1.get());
                        output.accept(ModBlocks.GRAY_STAINED_TRAPDOOR_1.get());
                        output.accept(ModBlocks.BLACK_STAINED_TRAPDOOR_1.get());
                        output.accept(ModBlocks.BROWN_STAINED_TRAPDOOR_1.get());
//TRAPDOOR 2//
                        output.accept(ModBlocks.RED_STAINED_TRAPDOOR_2.get());
                        output.accept(ModBlocks.ORANGE_STAINED_TRAPDOOR_2.get());
                        output.accept(ModBlocks.YELLOW_STAINED_TRAPDOOR_2.get());
                        output.accept(ModBlocks.LIME_STAINED_TRAPDOOR_2.get());
                        output.accept(ModBlocks.GREEN_STAINED_TRAPDOOR_2.get());
                        output.accept(ModBlocks.CYAN_STAINED_TRAPDOOR_2.get());
                        output.accept(ModBlocks.LIGHT_BLUE_STAINED_TRAPDOOR_2.get());
                        output.accept(ModBlocks.BLUE_STAINED_TRAPDOOR_2.get());
                        output.accept(ModBlocks.PURPLE_STAINED_TRAPDOOR_2.get());
                        output.accept(ModBlocks.MAGENTA_STAINED_TRAPDOOR_2.get());
                        output.accept(ModBlocks.PINK_STAINED_TRAPDOOR_2.get());
                        output.accept(ModBlocks.WHITE_STAINED_TRAPDOOR_2.get());
                        output.accept(ModBlocks.LIGHT_GRAY_STAINED_TRAPDOOR_2.get());
                        output.accept(ModBlocks.GRAY_STAINED_TRAPDOOR_2.get());
                        output.accept(ModBlocks.BLACK_STAINED_TRAPDOOR_2.get());
                        output.accept(ModBlocks.BROWN_STAINED_TRAPDOOR_2.get());
//TRAPDOOR 3//
                        output.accept(ModBlocks.RED_STAINED_TRAPDOOR_3.get());
                        output.accept(ModBlocks.ORANGE_STAINED_TRAPDOOR_3.get());
                        output.accept(ModBlocks.YELLOW_STAINED_TRAPDOOR_3.get());
                        output.accept(ModBlocks.LIME_STAINED_TRAPDOOR_3.get());
                        output.accept(ModBlocks.GREEN_STAINED_TRAPDOOR_3.get());
                        output.accept(ModBlocks.CYAN_STAINED_TRAPDOOR_3.get());
                        output.accept(ModBlocks.LIGHT_BLUE_STAINED_TRAPDOOR_3.get());
                        output.accept(ModBlocks.BLUE_STAINED_TRAPDOOR_3.get());
                        output.accept(ModBlocks.PURPLE_STAINED_TRAPDOOR_3.get());
                        output.accept(ModBlocks.MAGENTA_STAINED_TRAPDOOR_3.get());
                        output.accept(ModBlocks.PINK_STAINED_TRAPDOOR_3.get());
                        output.accept(ModBlocks.WHITE_STAINED_TRAPDOOR_3.get());
                        output.accept(ModBlocks.LIGHT_GRAY_STAINED_TRAPDOOR_3.get());
                        output.accept(ModBlocks.GRAY_STAINED_TRAPDOOR_3.get());
                        output.accept(ModBlocks.BLACK_STAINED_TRAPDOOR_3.get());
                        output.accept(ModBlocks.BROWN_STAINED_TRAPDOOR_3.get());
//TRAPDOOR 4//
                        output.accept(ModBlocks.RED_STAINED_TRAPDOOR_4.get());
                        output.accept(ModBlocks.ORANGE_STAINED_TRAPDOOR_4.get());
                        output.accept(ModBlocks.YELLOW_STAINED_TRAPDOOR_4.get());
                        output.accept(ModBlocks.LIME_STAINED_TRAPDOOR_4.get());
                        output.accept(ModBlocks.GREEN_STAINED_TRAPDOOR_4.get());
                        output.accept(ModBlocks.CYAN_STAINED_TRAPDOOR_4.get());
                        output.accept(ModBlocks.LIGHT_BLUE_STAINED_TRAPDOOR_4.get());
                        output.accept(ModBlocks.BLUE_STAINED_TRAPDOOR_4.get());
                        output.accept(ModBlocks.PURPLE_STAINED_TRAPDOOR_4.get());
                        output.accept(ModBlocks.MAGENTA_STAINED_TRAPDOOR_4.get());
                        output.accept(ModBlocks.PINK_STAINED_TRAPDOOR_4.get());
                        output.accept(ModBlocks.WHITE_STAINED_TRAPDOOR_4.get());
                        output.accept(ModBlocks.LIGHT_GRAY_STAINED_TRAPDOOR_4.get());
                        output.accept(ModBlocks.GRAY_STAINED_TRAPDOOR_4.get());
                        output.accept(ModBlocks.BLACK_STAINED_TRAPDOOR_4.get());
                        output.accept(ModBlocks.BROWN_STAINED_TRAPDOOR_4.get());

                        output.accept(ModBlocks.RED_STAINED_CHEST.get());
                        output.accept(ModBlocks.ORANGE_STAINED_CHEST.get());
                        output.accept(ModBlocks.YELLOW_STAINED_CHEST.get());
                        output.accept(ModBlocks.LIME_STAINED_CHEST.get());
                        output.accept(ModBlocks.GREEN_STAINED_CHEST.get());
                        output.accept(ModBlocks.CYAN_STAINED_CHEST.get());
                        output.accept(ModBlocks.LIGHT_BLUE_STAINED_CHEST.get());
                        output.accept(ModBlocks.BLUE_STAINED_CHEST.get());
                        output.accept(ModBlocks.PURPLE_STAINED_CHEST.get());
                        output.accept(ModBlocks.MAGENTA_STAINED_CHEST.get());
                        output.accept(ModBlocks.PINK_STAINED_CHEST.get());
                        output.accept(ModBlocks.WHITE_STAINED_CHEST.get());
                        output.accept(ModBlocks.LIGHT_GRAY_STAINED_CHEST.get());
                        output.accept(ModBlocks.GRAY_STAINED_CHEST.get());
                        output.accept(ModBlocks.BLACK_STAINED_CHEST.get());
                        output.accept(ModBlocks.BROWN_STAINED_CHEST.get());


                    })
                    .build());


    public static final RegistryObject<CreativeModeTab> OTHER = CREATIVE_MODE_TABS.register("other",
            () -> CreativeModeTab.builder().icon(() -> new ItemStack(ModBlocks.MAGENTA_BRICK_BLOCK.get()))
                    .title(Component.translatable("creativetab.other"))
                    .displayItems((parameters, output) -> {

                        //ESSENCES,OTHER//
                        output.accept(ModBlocks.MORTAR_PESTLE.get());
                        output.accept(ModBlocks.ORNAMENTAL_MUSHROOM.get());
                        output.accept(ModBlocks.FAIRY_GLOW_CUP.get());
                        output.accept(ModBlocks.EARTHEN_ESSENCE_BLOCK.get());
                        output.accept(ModBlocks.FLORAL_ESSENCE_BLOCK.get());
                        //   output.accept(ModBlocks.WALK_FLOWERS.get());
                        output.accept(ModBlocks.VINE_TIE.get());
                        output.accept(ModBlocks.ORNAMENTAL_PATH.get());
                        output.accept(ModBlocks.ORNAMENTAL_GRASS.get());


                        //COLORED CLAY//
                        //VASES//
                        output.accept(ModBlocks.VASE_RED.get());
                        output.accept(ModBlocks.VASE_ORANGE.get());
                        output.accept(ModBlocks.VASE_YELLOW.get());
                        output.accept(ModBlocks.VASE_LIME.get());
                        output.accept(ModBlocks.VASE_GREEN.get());
                        output.accept(ModBlocks.VASE_CYAN.get());
                        output.accept(ModBlocks.VASE_LIGHT_BLUE.get());
                        output.accept(ModBlocks.VASE_BLUE.get());
                        output.accept(ModBlocks.VASE_PURPLE.get());
                        output.accept(ModBlocks.VASE_MAGENTA.get());
                        output.accept(ModBlocks.VASE_PINK.get());
                        output.accept(ModBlocks.VASE_WHITE.get());
                        output.accept(ModBlocks.VASE_LIGHT_GRAY.get());
                        output.accept(ModBlocks.VASE_GRAY.get());
                        output.accept(ModBlocks.VASE_BLACK.get());
                        output.accept(ModBlocks.VASE_BROWN.get());


                        //BLOCKS//
                        output.accept(ModBlocks.RED_CLAY_BLOCK.get());
                        output.accept(ModBlocks.ORANGE_CLAY_BLOCK.get());
                        output.accept(ModBlocks.YELLOW_CLAY_BLOCK.get());
                        output.accept(ModBlocks.LIME_CLAY_BLOCK.get());
                        output.accept(ModBlocks.GREEN_CLAY_BLOCK.get());
                        output.accept(ModBlocks.CYAN_CLAY_BLOCK.get());
                        output.accept(ModBlocks.LIGHT_BLUE_CLAY_BLOCK.get());
                        output.accept(ModBlocks.BLUE_CLAY_BLOCK.get());
                        output.accept(ModBlocks.PURPLE_CLAY_BLOCK.get());
                        output.accept(ModBlocks.MAGENTA_CLAY_BLOCK.get());
                        output.accept(ModBlocks.PINK_CLAY_BLOCK.get());
                        output.accept(ModBlocks.WHITE_CLAY_BLOCK.get());
                        output.accept(ModBlocks.LIGHT_GRAY_CLAY_BLOCK.get());
                        output.accept(ModBlocks.GRAY_CLAY_BLOCK.get());
                        output.accept(ModBlocks.BLACK_CLAY_BLOCK.get());
                        output.accept(ModBlocks.BROWN_CLAY_BLOCK.get());
                        //BRICKS-SMALL//
                        output.accept(ModBlocks.RED_BRICK_BLOCK.get());
                        output.accept(ModBlocks.ORANGE_BRICK_BLOCK.get());
                        output.accept(ModBlocks.YELLOW_BRICK_BLOCK.get());
                        output.accept(ModBlocks.LIME_BRICK_BLOCK.get());
                        output.accept(ModBlocks.GREEN_BRICK_BLOCK.get());
                        output.accept(ModBlocks.CYAN_BRICK_BLOCK.get());
                        output.accept(ModBlocks.LIGHT_BLUE_BRICK_BLOCK.get());
                        output.accept(ModBlocks.BLUE_BRICK_BLOCK.get());
                        output.accept(ModBlocks.PURPLE_BRICK_BLOCK.get());
                        output.accept(ModBlocks.MAGENTA_BRICK_BLOCK.get());
                        output.accept(ModBlocks.PINK_BRICK_BLOCK.get());
                        output.accept(ModBlocks.WHITE_BRICK_BLOCK.get());
                        output.accept(ModBlocks.LIGHT_GRAY_BRICK_BLOCK.get());
                        output.accept(ModBlocks.GRAY_BRICK_BLOCK.get());
                        output.accept(ModBlocks.BLACK_BRICK_BLOCK.get());
                        output.accept(ModBlocks.BROWN_BRICK_BLOCK.get());
                        //BRICKS-LARGE//
                        output.accept(ModBlocks.RED_LARGE_BRICK_BLOCK.get());
                        output.accept(ModBlocks.ORANGE_LARGE_BRICK_BLOCK.get());
                        output.accept(ModBlocks.YELLOW_LARGE_BRICK_BLOCK.get());
                        output.accept(ModBlocks.LIME_LARGE_BRICK_BLOCK.get());
                        output.accept(ModBlocks.GREEN_LARGE_BRICK_BLOCK.get());
                        output.accept(ModBlocks.CYAN_LARGE_BRICK_BLOCK.get());
                        output.accept(ModBlocks.LIGHT_BLUE_LARGE_BRICK_BLOCK.get());
                        output.accept(ModBlocks.BLUE_LARGE_BRICK_BLOCK.get());
                        output.accept(ModBlocks.PURPLE_LARGE_BRICK_BLOCK.get());
                        output.accept(ModBlocks.MAGENTA_LARGE_BRICK_BLOCK.get());
                        output.accept(ModBlocks.PINK_LARGE_BRICK_BLOCK.get());
                        output.accept(ModBlocks.WHITE_LARGE_BRICK_BLOCK.get());
                        output.accept(ModBlocks.LIGHT_GRAY_LARGE_BRICK_BLOCK.get());
                        output.accept(ModBlocks.GRAY_LARGE_BRICK_BLOCK.get());
                        output.accept(ModBlocks.BLACK_LARGE_BRICK_BLOCK.get());
                        output.accept(ModBlocks.BROWN_LARGE_BRICK_BLOCK.get());
                        //BLOCKS-STAIRS//
                        output.accept(ModBlocks.RED_CLAY_STAIRS.get());
                        output.accept(ModBlocks.ORANGE_CLAY_STAIRS.get());
                        output.accept(ModBlocks.YELLOW_CLAY_STAIRS.get());
                        output.accept(ModBlocks.LIME_CLAY_STAIRS.get());
                        output.accept(ModBlocks.GREEN_CLAY_STAIRS.get());
                        output.accept(ModBlocks.CYAN_CLAY_STAIRS.get());
                        output.accept(ModBlocks.LIGHT_BLUE_CLAY_STAIRS.get());
                        output.accept(ModBlocks.BLUE_CLAY_STAIRS.get());
                        output.accept(ModBlocks.PURPLE_CLAY_STAIRS.get());
                        output.accept(ModBlocks.MAGENTA_CLAY_STAIRS.get());
                        output.accept(ModBlocks.PINK_CLAY_STAIRS.get());
                        output.accept(ModBlocks.WHITE_CLAY_STAIRS.get());
                        output.accept(ModBlocks.LIGHT_GRAY_CLAY_STAIRS.get());
                        output.accept(ModBlocks.GRAY_CLAY_STAIRS.get());
                        output.accept(ModBlocks.BLACK_CLAY_STAIRS.get());
                        output.accept(ModBlocks.BROWN_CLAY_STAIRS.get());
                        //BRICKS-SMALL-STAIRS//
                        output.accept(ModBlocks.RED_BRICK_STAIRS.get());
                        output.accept(ModBlocks.ORANGE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.YELLOW_BRICK_STAIRS.get());
                        output.accept(ModBlocks.LIME_BRICK_STAIRS.get());
                        output.accept(ModBlocks.GREEN_BRICK_STAIRS.get());
                        output.accept(ModBlocks.CYAN_BRICK_STAIRS.get());
                        output.accept(ModBlocks.LIGHT_BLUE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.BLUE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.PURPLE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.MAGENTA_BRICK_STAIRS.get());
                        output.accept(ModBlocks.PINK_BRICK_STAIRS.get());
                        output.accept(ModBlocks.WHITE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.LIGHT_GRAY_BRICK_STAIRS.get());
                        output.accept(ModBlocks.GRAY_BRICK_STAIRS.get());
                        output.accept(ModBlocks.BLACK_BRICK_STAIRS.get());
                        output.accept(ModBlocks.BROWN_BRICK_STAIRS.get());
                        //BRICKS-LARGE-STAIRS//
                        output.accept(ModBlocks.RED_LARGE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.ORANGE_LARGE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.YELLOW_LARGE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.LIME_LARGE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.GREEN_LARGE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.CYAN_LARGE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.LIGHT_BLUE_LARGE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.BLUE_LARGE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.PURPLE_LARGE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.MAGENTA_LARGE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.PINK_LARGE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.WHITE_LARGE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.LIGHT_GRAY_LARGE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.GRAY_LARGE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.BLACK_LARGE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.BROWN_LARGE_BRICK_STAIRS.get());
                        //BLOCKS-SLABS//
                        output.accept(ModBlocks.RED_CLAY_SLAB.get());
                        output.accept(ModBlocks.ORANGE_CLAY_SLAB.get());
                        output.accept(ModBlocks.YELLOW_CLAY_SLAB.get());
                        output.accept(ModBlocks.LIME_CLAY_SLAB.get());
                        output.accept(ModBlocks.GREEN_CLAY_SLAB.get());
                        output.accept(ModBlocks.CYAN_CLAY_SLAB.get());
                        output.accept(ModBlocks.LIGHT_BLUE_CLAY_SLAB.get());
                        output.accept(ModBlocks.BLUE_CLAY_SLAB.get());
                        output.accept(ModBlocks.PURPLE_CLAY_SLAB.get());
                        output.accept(ModBlocks.MAGENTA_CLAY_SLAB.get());
                        output.accept(ModBlocks.PINK_CLAY_SLAB.get());
                        output.accept(ModBlocks.WHITE_CLAY_SLAB.get());
                        output.accept(ModBlocks.LIGHT_GRAY_CLAY_SLAB.get());
                        output.accept(ModBlocks.GRAY_CLAY_SLAB.get());
                        output.accept(ModBlocks.BLACK_CLAY_SLAB.get());
                        output.accept(ModBlocks.BROWN_CLAY_SLAB.get());
                        //BRICKS-SMALL-SLABS//
                        output.accept(ModBlocks.RED_BRICK_SLAB.get());
                        output.accept(ModBlocks.ORANGE_BRICK_SLAB.get());
                        output.accept(ModBlocks.YELLOW_BRICK_SLAB.get());
                        output.accept(ModBlocks.LIME_BRICK_SLAB.get());
                        output.accept(ModBlocks.GREEN_BRICK_SLAB.get());
                        output.accept(ModBlocks.CYAN_BRICK_SLAB.get());
                        output.accept(ModBlocks.LIGHT_BLUE_BRICK_SLAB.get());
                        output.accept(ModBlocks.BLUE_BRICK_SLAB.get());
                        output.accept(ModBlocks.PURPLE_BRICK_SLAB.get());
                        output.accept(ModBlocks.MAGENTA_BRICK_SLAB.get());
                        output.accept(ModBlocks.PINK_BRICK_SLAB.get());
                        output.accept(ModBlocks.WHITE_BRICK_SLAB.get());
                        output.accept(ModBlocks.LIGHT_GRAY_BRICK_SLAB.get());
                        output.accept(ModBlocks.GRAY_BRICK_SLAB.get());
                        output.accept(ModBlocks.BLACK_BRICK_SLAB.get());
                        output.accept(ModBlocks.BROWN_BRICK_SLAB.get());
                        //BRICKS-LARGE-SLABS//
                        output.accept(ModBlocks.RED_LARGE_BRICK_SLAB.get());
                        output.accept(ModBlocks.ORANGE_LARGE_BRICK_SLAB.get());
                        output.accept(ModBlocks.YELLOW_LARGE_BRICK_SLAB.get());
                        output.accept(ModBlocks.LIME_LARGE_BRICK_SLAB.get());
                        output.accept(ModBlocks.GREEN_LARGE_BRICK_SLAB.get());
                        output.accept(ModBlocks.CYAN_LARGE_BRICK_SLAB.get());
                        output.accept(ModBlocks.LIGHT_BLUE_LARGE_BRICK_SLAB.get());
                        output.accept(ModBlocks.BLUE_LARGE_BRICK_SLAB.get());
                        output.accept(ModBlocks.PURPLE_LARGE_BRICK_SLAB.get());
                        output.accept(ModBlocks.MAGENTA_LARGE_BRICK_SLAB.get());
                        output.accept(ModBlocks.PINK_LARGE_BRICK_SLAB.get());
                        output.accept(ModBlocks.WHITE_LARGE_BRICK_SLAB.get());
                        output.accept(ModBlocks.LIGHT_GRAY_LARGE_BRICK_SLAB.get());
                        output.accept(ModBlocks.GRAY_LARGE_BRICK_SLAB.get());
                        output.accept(ModBlocks.BLACK_LARGE_BRICK_SLAB.get());
                        output.accept(ModBlocks.BROWN_LARGE_BRICK_SLAB.get());

//ORES//
                        output.accept(ModBlocks.JASPER_ORE.get());
                        output.accept(ModBlocks.CARNELIAN_ORE.get());
                        output.accept(ModBlocks.CITRINE_ORE.get());
                        output.accept(ModBlocks.AVENTURINE_ORE.get());
                        output.accept(ModBlocks.JADE_ORE.get());
                        output.accept(ModBlocks.CHALCOPYRITE_ORE.get());
                        output.accept(ModBlocks.LABRADORITE_ORE.get());
                        output.accept(ModBlocks.MOONSTONE_ORE.get());
                        output.accept(ModBlocks.SODALITE_ORE.get());
                        output.accept(ModBlocks.AMETHYST_ORE.get());
                        output.accept(ModBlocks.ROSE_QUARTZ_ORE.get());
                        output.accept(ModBlocks.MICA_ORE.get());

                        output.accept(ModBlocks.DEEPSLATE_JASPER_ORE.get());
                        output.accept(ModBlocks.DEEPSLATE_CARNELIAN_ORE.get());
                        output.accept(ModBlocks.DEEPSLATE_CITRINE_ORE.get());
                        output.accept(ModBlocks.DEEPSLATE_AVENTURINE_ORE.get());
                        output.accept(ModBlocks.DEEPSLATE_JADE_ORE.get());
                        output.accept(ModBlocks.DEEPSLATE_CHALCOPYRITE_ORE.get());
                        output.accept(ModBlocks.DEEPSLATE_LABRADORITE_ORE.get());
                        output.accept(ModBlocks.DEEPSLATE_MOONSTONE_ORE.get());
                        output.accept(ModBlocks.DEEPSLATE_SODALITE_ORE.get());
                        output.accept(ModBlocks.DEEPSLATE_AMETHYST_ORE.get());
                        output.accept(ModBlocks.DEEPSLATE_ROSE_QUARTZ_ORE.get());
                        output.accept(ModBlocks.DEEPSLATE_MICA_ORE.get());

//GEM BLOCKS//
                        output.accept(ModBlocks.JASPER_BLOCK.get());
                        output.accept(ModBlocks.CARNELIAN_BLOCK.get());
                        output.accept(ModBlocks.CITRINE_BLOCK.get());
                        output.accept(ModBlocks.AVENTURINE_BLOCK.get());
                        output.accept(ModBlocks.JADE_BLOCK.get());
                        output.accept(ModBlocks.CHALCOPYRITE_BLOCK.get());
                        output.accept(ModBlocks.LABRADORITE_BLOCK.get());
                        output.accept(ModBlocks.MOONSTONE_BLOCK.get());
                        output.accept(ModBlocks.SODALITE_BLOCK.get());
                        output.accept(ModBlocks.AMETHYST_BLOCK.get());
                        output.accept(ModBlocks.ROSE_QUARTZ_BLOCK.get());
                        output.accept(ModBlocks.MICA_BLOCK.get());

//GEM TILES//
                        output.accept(ModBlocks.JASPER_1.get());
                        output.accept(ModBlocks.CARNELIAN_1.get());
                        output.accept(ModBlocks.CITRINE_1.get());
                        output.accept(ModBlocks.AVENTURINE_1.get());
                        output.accept(ModBlocks.JADE_1.get());
                        output.accept(ModBlocks.CHALCOPYRITE_1.get());
                        output.accept(ModBlocks.LABRADORITE_1.get());
                        output.accept(ModBlocks.MOONSTONE_1.get());
                        output.accept(ModBlocks.SODALITE_1.get());
                        output.accept(ModBlocks.AMETHYST_1.get());
                        output.accept(ModBlocks.ROSE_QUARTZ_1.get());
                        output.accept(ModBlocks.MICA_1.get());

                        output.accept(ModBlocks.JASPER_2.get());
                        output.accept(ModBlocks.CARNELIAN_2.get());
                        output.accept(ModBlocks.CITRINE_2.get());
                        output.accept(ModBlocks.AVENTURINE_2.get());
                        output.accept(ModBlocks.JADE_2.get());
                        output.accept(ModBlocks.CHALCOPYRITE_2.get());
                        output.accept(ModBlocks.LABRADORITE_2.get());
                        output.accept(ModBlocks.MOONSTONE_2.get());
                        output.accept(ModBlocks.SODALITE_2.get());
                        output.accept(ModBlocks.AMETHYST_2.get());
                        output.accept(ModBlocks.ROSE_QUARTZ_2.get());
                        output.accept(ModBlocks.MICA_2.get());

                        output.accept(ModBlocks.JASPER_3.get());
                        output.accept(ModBlocks.CARNELIAN_3.get());
                        output.accept(ModBlocks.CITRINE_3.get());
                        output.accept(ModBlocks.AVENTURINE_3.get());
                        output.accept(ModBlocks.JADE_3.get());
                        output.accept(ModBlocks.CHALCOPYRITE_3.get());
                        output.accept(ModBlocks.LABRADORITE_3.get());
                        output.accept(ModBlocks.MOONSTONE_3.get());
                        output.accept(ModBlocks.SODALITE_3.get());
                        output.accept(ModBlocks.AMETHYST_3.get());
                        output.accept(ModBlocks.ROSE_QUARTZ_3.get());
                        output.accept(ModBlocks.MICA_3.get());

                        output.accept(ModBlocks.JASPER_4.get());
                        output.accept(ModBlocks.CARNELIAN_4.get());
                        output.accept(ModBlocks.CITRINE_4.get());
                        output.accept(ModBlocks.AVENTURINE_4.get());
                        output.accept(ModBlocks.JADE_4.get());
                        output.accept(ModBlocks.CHALCOPYRITE_4.get());
                        output.accept(ModBlocks.LABRADORITE_4.get());
                        output.accept(ModBlocks.MOONSTONE_4.get());
                        output.accept(ModBlocks.SODALITE_4.get());
                        output.accept(ModBlocks.AMETHYST_4.get());
                        output.accept(ModBlocks.ROSE_QUARTZ_4.get());
                        output.accept(ModBlocks.MICA_4.get());

                        output.accept(ModBlocks.JASPER_5.get());
                        output.accept(ModBlocks.CARNELIAN_5.get());
                        output.accept(ModBlocks.CITRINE_5.get());
                        output.accept(ModBlocks.AVENTURINE_5.get());
                        output.accept(ModBlocks.JADE_5.get());
                        output.accept(ModBlocks.CHALCOPYRITE_5.get());
                        output.accept(ModBlocks.LABRADORITE_5.get());
                        output.accept(ModBlocks.MOONSTONE_5.get());
                        output.accept(ModBlocks.SODALITE_5.get());
                        output.accept(ModBlocks.AMETHYST_5.get());
                        output.accept(ModBlocks.ROSE_QUARTZ_5.get());
                        output.accept(ModBlocks.MICA_5.get());

                        output.accept(ModBlocks.JASPER_6.get());
                        output.accept(ModBlocks.CARNELIAN_6.get());
                        output.accept(ModBlocks.CITRINE_6.get());
                        output.accept(ModBlocks.AVENTURINE_6.get());
                        output.accept(ModBlocks.JADE_6.get());
                        output.accept(ModBlocks.CHALCOPYRITE_6.get());
                        output.accept(ModBlocks.LABRADORITE_6.get());
                        output.accept(ModBlocks.MOONSTONE_6.get());
                        output.accept(ModBlocks.SODALITE_6.get());
                        output.accept(ModBlocks.AMETHYST_6.get());
                        output.accept(ModBlocks.ROSE_QUARTZ_6.get());
                        output.accept(ModBlocks.MICA_6.get());

//GEM TILES-SLABS//
                        output.accept(ModBlocks.JASPER_1_SLAB.get());
                        output.accept(ModBlocks.CARNELIAN_1_SLAB.get());
                        output.accept(ModBlocks.CITRINE_1_SLAB.get());
                        output.accept(ModBlocks.AVENTURINE_1_SLAB.get());
                        output.accept(ModBlocks.JADE_1_SLAB.get());
                        output.accept(ModBlocks.CHALCOPYRITE_1_SLAB.get());
                        output.accept(ModBlocks.LABRADORITE_1_SLAB.get());
                        output.accept(ModBlocks.MOONSTONE_1_SLAB.get());
                        output.accept(ModBlocks.SODALITE_1_SLAB.get());
                        output.accept(ModBlocks.AMETHYST_1_SLAB.get());
                        output.accept(ModBlocks.ROSE_QUARTZ_1_SLAB.get());
                        output.accept(ModBlocks.MICA_1_SLAB.get());

                        output.accept(ModBlocks.JASPER_2_SLAB.get());
                        output.accept(ModBlocks.CARNELIAN_2_SLAB.get());
                        output.accept(ModBlocks.CITRINE_2_SLAB.get());
                        output.accept(ModBlocks.AVENTURINE_2_SLAB.get());
                        output.accept(ModBlocks.JADE_2_SLAB.get());
                        output.accept(ModBlocks.CHALCOPYRITE_2_SLAB.get());
                        output.accept(ModBlocks.LABRADORITE_2_SLAB.get());
                        output.accept(ModBlocks.MOONSTONE_2_SLAB.get());
                        output.accept(ModBlocks.SODALITE_2_SLAB.get());
                        output.accept(ModBlocks.AMETHYST_2_SLAB.get());
                        output.accept(ModBlocks.ROSE_QUARTZ_2_SLAB.get());
                        output.accept(ModBlocks.MICA_2_SLAB.get());

                        output.accept(ModBlocks.JASPER_3_SLAB.get());
                        output.accept(ModBlocks.CARNELIAN_3_SLAB.get());
                        output.accept(ModBlocks.CITRINE_3_SLAB.get());
                        output.accept(ModBlocks.AVENTURINE_3_SLAB.get());
                        output.accept(ModBlocks.JADE_3_SLAB.get());
                        output.accept(ModBlocks.CHALCOPYRITE_3_SLAB.get());
                        output.accept(ModBlocks.LABRADORITE_3_SLAB.get());
                        output.accept(ModBlocks.MOONSTONE_3_SLAB.get());
                        output.accept(ModBlocks.SODALITE_3_SLAB.get());
                        output.accept(ModBlocks.AMETHYST_3_SLAB.get());
                        output.accept(ModBlocks.ROSE_QUARTZ_3_SLAB.get());
                        output.accept(ModBlocks.MICA_3_SLAB.get());

                        output.accept(ModBlocks.JASPER_4_SLAB.get());
                        output.accept(ModBlocks.CARNELIAN_4_SLAB.get());
                        output.accept(ModBlocks.CITRINE_4_SLAB.get());
                        output.accept(ModBlocks.AVENTURINE_4_SLAB.get());
                        output.accept(ModBlocks.JADE_4_SLAB.get());
                        output.accept(ModBlocks.CHALCOPYRITE_4_SLAB.get());
                        output.accept(ModBlocks.LABRADORITE_4_SLAB.get());
                        output.accept(ModBlocks.MOONSTONE_4_SLAB.get());
                        output.accept(ModBlocks.SODALITE_4_SLAB.get());
                        output.accept(ModBlocks.AMETHYST_4_SLAB.get());
                        output.accept(ModBlocks.ROSE_QUARTZ_4_SLAB.get());
                        output.accept(ModBlocks.MICA_4_SLAB.get());

                        output.accept(ModBlocks.JASPER_5_SLAB.get());
                        output.accept(ModBlocks.CARNELIAN_5_SLAB.get());
                        output.accept(ModBlocks.CITRINE_5_SLAB.get());
                        output.accept(ModBlocks.AVENTURINE_5_SLAB.get());
                        output.accept(ModBlocks.JADE_5_SLAB.get());
                        output.accept(ModBlocks.CHALCOPYRITE_5_SLAB.get());
                        output.accept(ModBlocks.LABRADORITE_5_SLAB.get());
                        output.accept(ModBlocks.MOONSTONE_5_SLAB.get());
                        output.accept(ModBlocks.SODALITE_5_SLAB.get());
                        output.accept(ModBlocks.AMETHYST_5_SLAB.get());
                        output.accept(ModBlocks.ROSE_QUARTZ_5_SLAB.get());
                        output.accept(ModBlocks.MICA_5_SLAB.get());

                        output.accept(ModBlocks.JASPER_6_SLAB.get());
                        output.accept(ModBlocks.CARNELIAN_6_SLAB.get());
                        output.accept(ModBlocks.CITRINE_6_SLAB.get());
                        output.accept(ModBlocks.AVENTURINE_6_SLAB.get());
                        output.accept(ModBlocks.JADE_6_SLAB.get());
                        output.accept(ModBlocks.CHALCOPYRITE_6_SLAB.get());
                        output.accept(ModBlocks.LABRADORITE_6_SLAB.get());
                        output.accept(ModBlocks.MOONSTONE_6_SLAB.get());
                        output.accept(ModBlocks.SODALITE_6_SLAB.get());
                        output.accept(ModBlocks.AMETHYST_6_SLAB.get());
                        output.accept(ModBlocks.ROSE_QUARTZ_6_SLAB.get());
                        output.accept(ModBlocks.MICA_6_SLAB.get());

//GEM TILES- STAIRS//
                        output.accept(ModBlocks.JASPER_1_STAIRS.get());
                        output.accept(ModBlocks.CARNELIAN_1_STAIRS.get());
                        output.accept(ModBlocks.CITRINE_1_STAIRS.get());
                        output.accept(ModBlocks.AVENTURINE_1_STAIRS.get());
                        output.accept(ModBlocks.JADE_1_STAIRS.get());
                        output.accept(ModBlocks.CHALCOPYRITE_1_STAIRS.get());
                        output.accept(ModBlocks.LABRADORITE_1_STAIRS.get());
                        output.accept(ModBlocks.MOONSTONE_1_STAIRS.get());
                        output.accept(ModBlocks.SODALITE_1_STAIRS.get());
                        output.accept(ModBlocks.AMETHYST_1_STAIRS.get());
                        output.accept(ModBlocks.ROSE_QUARTZ_1_STAIRS.get());
                        output.accept(ModBlocks.MICA_1_STAIRS.get());

                        output.accept(ModBlocks.JASPER_2_STAIRS.get());
                        output.accept(ModBlocks.CARNELIAN_2_STAIRS.get());
                        output.accept(ModBlocks.CITRINE_2_STAIRS.get());
                        output.accept(ModBlocks.AVENTURINE_2_STAIRS.get());
                        output.accept(ModBlocks.JADE_2_STAIRS.get());
                        output.accept(ModBlocks.CHALCOPYRITE_2_STAIRS.get());
                        output.accept(ModBlocks.LABRADORITE_2_STAIRS.get());
                        output.accept(ModBlocks.MOONSTONE_2_STAIRS.get());
                        output.accept(ModBlocks.SODALITE_2_STAIRS.get());
                        output.accept(ModBlocks.AMETHYST_2_STAIRS.get());
                        output.accept(ModBlocks.ROSE_QUARTZ_2_STAIRS.get());
                        output.accept(ModBlocks.MICA_2_STAIRS.get());

                        output.accept(ModBlocks.JASPER_3_STAIRS.get());
                        output.accept(ModBlocks.CARNELIAN_3_STAIRS.get());
                        output.accept(ModBlocks.CITRINE_3_STAIRS.get());
                        output.accept(ModBlocks.AVENTURINE_3_STAIRS.get());
                        output.accept(ModBlocks.JADE_3_STAIRS.get());
                        output.accept(ModBlocks.CHALCOPYRITE_3_STAIRS.get());
                        output.accept(ModBlocks.LABRADORITE_3_STAIRS.get());
                        output.accept(ModBlocks.MOONSTONE_3_STAIRS.get());
                        output.accept(ModBlocks.SODALITE_3_STAIRS.get());
                        output.accept(ModBlocks.AMETHYST_3_STAIRS.get());
                        output.accept(ModBlocks.ROSE_QUARTZ_3_STAIRS.get());
                        output.accept(ModBlocks.MICA_3_STAIRS.get());

                        output.accept(ModBlocks.JASPER_4_STAIRS.get());
                        output.accept(ModBlocks.CARNELIAN_4_STAIRS.get());
                        output.accept(ModBlocks.CITRINE_4_STAIRS.get());
                        output.accept(ModBlocks.AVENTURINE_4_STAIRS.get());
                        output.accept(ModBlocks.JADE_4_STAIRS.get());
                        output.accept(ModBlocks.CHALCOPYRITE_4_STAIRS.get());
                        output.accept(ModBlocks.LABRADORITE_4_STAIRS.get());
                        output.accept(ModBlocks.MOONSTONE_4_STAIRS.get());
                        output.accept(ModBlocks.SODALITE_4_STAIRS.get());
                        output.accept(ModBlocks.AMETHYST_4_STAIRS.get());
                        output.accept(ModBlocks.ROSE_QUARTZ_4_STAIRS.get());
                        output.accept(ModBlocks.MICA_4_STAIRS.get());

                        output.accept(ModBlocks.JASPER_5_STAIRS.get());
                        output.accept(ModBlocks.CARNELIAN_5_STAIRS.get());
                        output.accept(ModBlocks.CITRINE_5_STAIRS.get());
                        output.accept(ModBlocks.AVENTURINE_5_STAIRS.get());
                        output.accept(ModBlocks.JADE_5_STAIRS.get());
                        output.accept(ModBlocks.CHALCOPYRITE_5_STAIRS.get());
                        output.accept(ModBlocks.LABRADORITE_5_STAIRS.get());
                        output.accept(ModBlocks.MOONSTONE_5_STAIRS.get());
                        output.accept(ModBlocks.SODALITE_5_STAIRS.get());
                        output.accept(ModBlocks.AMETHYST_5_STAIRS.get());
                        output.accept(ModBlocks.ROSE_QUARTZ_5_STAIRS.get());
                        output.accept(ModBlocks.MICA_5_STAIRS.get());

                        output.accept(ModBlocks.JASPER_6_STAIRS.get());
                        output.accept(ModBlocks.CARNELIAN_6_STAIRS.get());
                        output.accept(ModBlocks.CITRINE_6_STAIRS.get());
                        output.accept(ModBlocks.AVENTURINE_6_STAIRS.get());
                        output.accept(ModBlocks.JADE_6_STAIRS.get());
                        output.accept(ModBlocks.CHALCOPYRITE_6_STAIRS.get());
                        output.accept(ModBlocks.LABRADORITE_6_STAIRS.get());
                        output.accept(ModBlocks.MOONSTONE_6_STAIRS.get());
                        output.accept(ModBlocks.SODALITE_6_STAIRS.get());
                        output.accept(ModBlocks.AMETHYST_6_STAIRS.get());
                        output.accept(ModBlocks.ROSE_QUARTZ_6_STAIRS.get());
                        output.accept(ModBlocks.MICA_6_STAIRS.get());

                    })
                    .build());

}



